apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-app
  labels:
    app: devops-lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab-app
  template:
    metadata:
      labels:
        app: devops-lab-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: devops-lab-app
          image: acrdevopslab2025daniel.azurecr.io/devops-lab-app:05f414c68932d63f77e01e7b034773cd960f9a95
          ports:
            - containerPort: 80
    
